name: Build Ruby for GitHub Actions
on: push
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ 'ubuntu-16.04' ]
        ruby: [ 'ruby-2.3.8' ]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Clone ruby-build
      # run: git clone https://github.com/rbenv/ruby-build.git
      run: git clone --branch ruby23-openssl-linux https://github.com/eregon/ruby-build.git
    - name: Install ruby-build
      run: sudo ./ruby-build/install.sh

    - &list
      name: List versions
      run: ruby-build --definitions
    - *list

    - name: apt-get update on Ubuntu
      run: sudo apt-get update
      if: startsWith(matrix.os, 'ubuntu')
    # bison libyaml-dev libgdbm-dev libreadline-dev libncurses5-dev
    - run: sudo apt-get install -y libgdbm-dev libreadline-dev
      if: startsWith(matrix.os, 'ubuntu')

    - name: Build Ruby
      # TODO: fix version
      run: ruby-build --verbose 2.3.8 $HOME/.rubies/${{ matrix.ruby }}
      env:
        RUBY_CONFIGURE_OPTS: --disable-install-doc
    - name: Install Bundler if needed
      run: |
        if [ ! -e ~/.rubies/${{ matrix.ruby }}/bin/bundle ]; then
          export PATH="$HOME/.rubies/${{ matrix.ruby }}/bin:$PATH"
          gem install bundler --no-document
        fi

    - name: Basic test
      run: ~/.rubies/${{ matrix.ruby }}/bin/ruby --version
    - &openssl
      name: OpenSSL test
      run: ~/.rubies/${{ matrix.ruby }}/bin/ruby -ropen-uri -e 'puts open("https://rubygems.org/") { |f| f.read(2014) }'
    - *openssl

    - name: Create archive
      run: tar czf ${{ matrix.ruby }}-${{ matrix.os }}.tar.gz -C ~/.rubies ${{ matrix.ruby }}
