name: Build Ruby for GitHub Actions
on: push
jobs:
  build:
    strategy:
      matrix:
        os: [ 'windows-latest' ]
        ruby: [ 'ruby-2.6.5' ]
    runs-on: ${{ matrix.os }}
    steps:
    - run: ls C:/
    - run: echo $env:PATH
    - run: ruby --version
    - run: echo "::add-path::C:/Program Files/7-Zip"

    - run: |
        $(new-object net.webclient).DownloadFile("https://github.com/oneclick/rubyinstaller2/releases/download/RubyInstaller-2.6.5-1/rubyinstaller-devkit-2.6.5-1-x64.exe", "$pwd/ruby-setup.exe")
    - run: cmd /c ruby-setup.exe /verysilent /dir=C:/Ruby26

    # - name: Install Bundler if needed
    #   run: |
    #     if [ ! -e ~/.rubies/${{ matrix.ruby }}/bin/bundle ]; then
    #       export PATH="$HOME/.rubies/${{ matrix.ruby }}/bin:$PATH"
    #       gem install bundler --no-document
    #     fi

    - run: C:/Ruby26/bin/ridk version
    - run: |
        C:/Ruby26/bin/ridk enable
        C:/Ruby26/bin/ridk version

    - name: Basic test
      run: C:/Ruby26/bin/ruby --version
    - name: OpenSSL test
      run: C:/Ruby26/bin/ruby -ropen-uri -e 'puts open(%{https://rubygems.org/}) { |f| f.read(2014) }'

    - name: Create archive
      run: |
        7z a $env:GITHUB_WORKSPACE\${{ matrix.ruby }}-${{ matrix.os }}.7z Ruby26
      working-directory: C:/

    - uses: actions/upload-artifact@v1
      with:
        name: ${{ matrix.ruby }}-${{ matrix.os }}
        path: ${{ matrix.ruby }}-${{ matrix.os }}.7z

  test:
    needs: [build]
    strategy:
      matrix:
        os: [ 'windows-latest' ]
        ruby: [ 'ruby-2.6.5' ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/download-artifact@v1
      with:
        name: ${{ matrix.ruby }}-${{ matrix.os }}

    - run: |
        7z x $env:GITHUB_WORKSPACE\${{ matrix.ruby }}-${{ matrix.os }}\${{ matrix.ruby }}-${{ matrix.os }}.7z -oC:\

    - run: ls C:/Ruby26
    - run: echo "::add-path::C:/Ruby26/bin"

    - name: Basic test
      run: ruby --version
    - name: OpenSSL test
      run: ruby -ropen-uri -e 'puts open(%{https://rubygems.org/}) { |f| f.read(2014) }'
    - name: C extension test
      run: gem install json --no-document

    - run: which bundle
    - run: bundle --version
