name: Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: env
    - run: wget 'https://repo1.maven.org/maven2/org/jruby/jruby-dist/9.2.9.0/jruby-dist-9.2.9.0-bin.tar.gz'
    - run: tar xf jruby-dist-9.2.9.0-bin.tar.gz
    - run: ls
    - run: jruby-9.2.9.0/bin/jruby --version
    - run: echo "::add-path::$PWD/jruby-9.2.9.0/bin"
    - run: jruby --version
    - run: jruby -ryaml -e 'p YAML'
    - run: gem env
    - run: gem install bundler
