name: Build Ruby for GitHub Actions
on: push
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ 'windows-latest' ]
        ruby: [ 'ruby-2.6.5' ]
    runs-on: ${{ matrix.os }}
    steps:
    - run: |
        $(new-object net.webclient).DownloadFile("https://github.com/oneclick/rubyinstaller2/releases/download/RubyInstaller-2.6.5-1/rubyinstaller-2.6.5-1-x64.exe", "$pwd/ruby-setup.exe")
    - run: cmd /c ruby-setup.exe /verysilent /dir=C:/Ruby26

    # - name: Install Bundler if needed
    #   run: |
    #     if [ ! -e ~/.rubies/${{ matrix.ruby }}/bin/bundle ]; then
    #       export PATH="$HOME/.rubies/${{ matrix.ruby }}/bin:$PATH"
    #       gem install bundler --no-document
    #     fi

    - name: Basic test
      run: C:/Ruby26/bin/ruby --version
    - name: OpenSSL test
      run: C:/Ruby26/bin/ruby -ropen-uri -e 'puts open(%{https://rubygems.org/}) { |f| f.read(2014) }'

    - name: Create archive
      run: |
        tar czf ${{ matrix.ruby }}-${{ matrix.os }}.tar.gz -C C:/ Ruby26
