name: Build Ruby for GitHub Actions
on: [push]
jobs:
  # Build stable releases
  build:
    if: false
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-16.04, ubuntu-18.04, macos-latest ]
        ruby: [ truffleruby-19.3.1 ]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Set tag name
      id: info
      run: |
        tag=builds-newer-openssl
        echo "::set-output name=tag::$tag"
    - name: Check if already built
      run: '! curl -s --head --fail https://github.com/eregon/ruby-install-builder/releases/download/${{ steps.info.outputs.tag }}/${{ matrix.ruby }}-${{ matrix.os }}.tar.gz'

    - name: Clone ruby-install
      run: git clone https://github.com/postmodern/ruby-install.git
    - name: Install ruby-install
      run: sudo make install
      working-directory: ./ruby-install

    - name: List versions
      run: ruby-install

    - name: apt-get update on Ubuntu
      run: sudo apt-get update
      if: startsWith(matrix.os, 'ubuntu')
    - name: Install system ruby for ruby-2.5.2
      run: sudo apt-get install ruby
      if: startsWith(matrix.os, 'ubuntu') && matrix.ruby == 'ruby-2.5.2'

    - name: Build Ruby
      run: ruby-install ${{ matrix.ruby }} -- --disable-install-doc
    - name: Install Bundler if needed
      run: |
        if [ ! -e ~/.rubies/${{ matrix.ruby }}/bin/bundle ]; then
          export PATH="$HOME/.rubies/${{ matrix.ruby }}/bin:$PATH"
          gem install bundler -v '~> 1' --no-document
        fi

    - name: Basic test
      run: ~/.rubies/${{ matrix.ruby }}/bin/ruby --version
    - name: OpenSSL test
      run: ~/.rubies/${{ matrix.ruby }}/bin/ruby -ropen-uri -e 'puts open("https://rubygems.org/") { |f| f.read(1024) }'
    - name: Bundler version
      run: ~/.rubies/${{ matrix.ruby }}/bin/bundle --version

    - name: Create archive
      run: tar czf ${{ matrix.ruby }}-${{ matrix.os }}.tar.gz -C ~/.rubies ${{ matrix.ruby }}
    - name: Upload Built Ruby
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        # curl -s 'https://api.github.com/repos/eregon/ruby-install-builder/releases/tags/$TAG' | jq -r .upload_url
        upload_url: 'https://uploads.github.com/repos/eregon/ruby-install-builder/releases/22947744/assets{?name,label}'
        asset_path: ${{ matrix.ruby }}-${{ matrix.os }}.tar.gz
        asset_name: ${{ matrix.ruby }}-${{ matrix.os }}.tar.gz
        asset_content_type: application/gzip

  buildJRubyWindows:
    if: true
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest ]
        ruby: [ jruby-9.2.9.0 ]
        jruby-version: [ 9.2.9.0 ]
        underscore-version: [ 9_2_9_0 ]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Set tag name
      id: info
      run: |
        tag=builds-newer-openssl
        echo "::set-output name=tag::$tag"
      shell: bash
    # - name: Check if already built
    #   run: '! curl -s --head --fail https://github.com/eregon/ruby-install-builder/releases/download/${{ steps.info.outputs.tag }}/${{ matrix.ruby }}-${{ matrix.os }}.tar.gz'
    #   shell: bash

    - run: curl --fail -L -O 'https://repo1.maven.org/maven2/org/jruby/jruby-dist/9.2.9.0/jruby-dist-9.2.9.0-bin.tar.gz'
      shell: bash
    - name: Build JRuby
      shell: bash
      run: |
        mkdir ~/.rubies
        tar xf jruby-dist-9.2.9.0-bin.tar.gz -C ~/.rubies
        cd ~/.rubies/${{ matrix.ruby }}/bin
        cp jruby.exe ruby.exe
      # echo -en "@ECHO OFF\r\n@\"%~dp0jruby.exe\" %*\r\n" > ruby.bat

    - run: ~/.rubies/${{ matrix.ruby }}/bin/jruby.exe --version
    - run: ~/.rubies/${{ matrix.ruby }}/bin/ruby.exe --version

    - name: Install Bundler if needed
      shell: bash
      run: |
        if [ ! -e ~/.rubies/${{ matrix.ruby }}/bin/bundle ]; then
          export PATH="$HOME/.rubies/${{ matrix.ruby }}/bin:$PATH"
          gem install bundler -v '~> 1' --no-document
        fi

    - name: Basic test (Bash)
      run: ~/.rubies/${{ matrix.ruby }}/bin/jruby.bash --version
      shell: bash
    - name: OpenSSL test (Bash)
      run: ~/.rubies/${{ matrix.ruby }}/bin/jruby.bash -ropen-uri -e 'puts open(%{https://rubygems.org/}) { |f| f.read(1024) }'
      shell: bash
    - name: Bundler version (Bash)
      run: ~/.rubies/${{ matrix.ruby }}/bin/jruby.bash -S bundle --version
      shell: bash

    - name: Basic test (exe)
      run: ~/.rubies/${{ matrix.ruby }}/bin/jruby.exe --version
    - name: OpenSSL test (exe)
      run: ~/.rubies/${{ matrix.ruby }}/bin/jruby.exe -ropen-uri -e 'puts open(%{https://rubygems.org/}) { |f| f.read(1024) }'
    - name: Bundler version (exe)
      run: ~/.rubies/${{ matrix.ruby }}/bin/jruby.exe -S bundle --version

    # - name: Create archive
    #   run: tar czf ${{ matrix.ruby }}-${{ matrix.os }}.tar.gz -C ~/.rubies ${{ matrix.ruby }}
    #   shell: bash
    # - name: Upload Built Ruby
    #   uses: actions/upload-release-asset@v1.0.1
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   with:
    #     # curl -s 'https://api.github.com/repos/eregon/ruby-install-builder/releases/tags/$TAG' | jq -r .upload_url
    #     upload_url: 'https://uploads.github.com/repos/eregon/ruby-install-builder/releases/22947744/assets{?name,label}'
    #     asset_path: ${{ matrix.ruby }}-${{ matrix.os }}.tar.gz
    #     asset_name: ${{ matrix.ruby }}-${{ matrix.os }}.tar.gz
    #     asset_content_type: application/gzip

  # Ruby 2.3 needs OpenSSL 1.0.2 which cannot be installed on Ubuntu 16.04 and macos-latest.
  # To workaround that, we use ruby-build which builds its own OpenSSL.
  build23:
    if: false
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-16.04, ubuntu-18.04, macos-latest ]
        ruby-version: [ 2.3.0, 2.3.1, 2.3.2, 2.3.3, 2.3.4, 2.3.5, 2.3.6, 2.3.7, 2.3.8 ]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Set tag name
      id: info
      run: |
        tag=builds-newer-openssl
        echo "::set-output name=tag::$tag"
    - name: Check if already built
      run: '! curl -s --head --fail https://github.com/eregon/ruby-install-builder/releases/download/${{ steps.info.outputs.tag }}/ruby-${{ matrix.ruby-version }}-${{ matrix.os }}.tar.gz'

    - name: Clone ruby-build
      run: git clone --branch ruby23-openssl-linux https://github.com/eregon/ruby-build.git
    - name: Install ruby-build
      run: sudo ./ruby-build/install.sh

    - name: List versions
      run: ruby-build --definitions

    - name: apt-get update on Ubuntu
      run: sudo apt-get update
      if: startsWith(matrix.os, 'ubuntu')
    - run: sudo apt-get install -y libyaml-dev libgdbm-dev libreadline-dev libncurses5-dev
      if: startsWith(matrix.os, 'ubuntu')

    - name: Build Ruby
      run: ruby-build --verbose ${{ matrix.ruby-version }} $HOME/.rubies/ruby-${{ matrix.ruby-version }}
      env:
        RUBY_CONFIGURE_OPTS: --disable-install-doc
    - name: Install Bundler if needed
      run: |
        if [ ! -e ~/.rubies/ruby-${{ matrix.ruby-version }}/bin/bundle ]; then
          export PATH="$HOME/.rubies/ruby-${{ matrix.ruby-version }}/bin:$PATH"
          gem install bundler -v '~> 1' --no-document
        fi

    - name: Basic test
      run: ~/.rubies/ruby-${{ matrix.ruby-version }}/bin/ruby --version
    - name: OpenSSL test
      run: ~/.rubies/ruby-${{ matrix.ruby-version }}/bin/ruby -ropen-uri -e 'puts open("https://rubygems.org/") { |f| f.read(1024) }'
    - name: Bundler version
      run: ~/.rubies/ruby-${{ matrix.ruby-version }}/bin/bundle --version

    - name: Create archive
      run: tar czf ruby-${{ matrix.ruby-version }}-${{ matrix.os }}.tar.gz -C ~/.rubies ruby-${{ matrix.ruby-version }}
    - name: Upload Built Ruby
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        # curl -s 'https://api.github.com/repos/eregon/ruby-install-builder/releases/tags/$TAG' | jq -r .upload_url
        upload_url: 'https://uploads.github.com/repos/eregon/ruby-install-builder/releases/22947744/assets{?name,label}'
        asset_path: ruby-${{ matrix.ruby-version }}-${{ matrix.os }}.tar.gz
        asset_name: ruby-${{ matrix.ruby-version }}-${{ matrix.os }}.tar.gz
        asset_content_type: application/gzip
